version: '3'

services:
  landing-service:
    build: ./landing
    ports:
      - "5050:5050"
    networks:
      - my-net
    depends_on:
      - addition-service
      - subtraction-service
      - multiplication-service
      - division-service
      - modulus-service
      - exponent-service
      - greaterthan-service
    environment:
      - ADDITION_SERVICE_URL=http://addition-service:5051/
      - SUBTRACTION_SERVICE_URL=http://subtraction-service:5052/
      - MULTIPLICATION_SERVICE_URL=http://multiplication-service:5053/
      - DIVISION_SERVICE_URL=http://division-service:5054/
      - MODULUS_SERVICE_URL=http://modulus-service:5055/
      - EXONENT_SERVICE_URL=http://exponent-service:5056/
      - GREATERTHAN_SERVICE_URL=htttp://greaterthan-service:5057/

  addition-service:
    build: ./addition
    expose:
      - "5051"
    ports:
      - "5051:5051"
    networks:
      - my-net

  subtraction-service:
    build: ./subtraction
    expose: 
      - "5052"
    ports:
      - "5052:5052"
    networks:
      - my-net

  multiplication-service:
    build: ./multiplication
    expose:
      - "5053"
    ports:
      - "5053:5053"
    networks:
      - my-net

  division-service:
    build: ./division
    expose:
      - "5054"
    ports:
      - "5054:5054"
    networks:
      - my-net
      
  modulus-service:
    build: ./modulus
    expose:
      - "5055"
    ports:
      - "5055:5055"
    networks:
      - my-net
      
  exponent-service:
    build: ./exponent
    expose:
      - "5056"
    ports:
      - "5056:5056"
    networks:
      - my-net
 
  greaterthan-service:
    build: ./greaterthan
    expose:
      - "5057"
    ports:
      - "5057:5057"
    networks:
      - my-net    

networks:
  my-net:
    driver: bridge
